### ISSUE TITLE
Docker Issue

### ISSUE THREAD

**Issue by janstadt** [jez500/pricebuddy#2]
I prefer to persist my db and data to the host but im having issues with getting the app up and running.  Containers run, but the app container is unavailable. laravel logs attached. I changed ports for a few things as i have existing containers that use the defined ports.

[laravel.log](https://github.com/user-attachments/files/19430334/laravel.log)

```
services:
  app:
    build:
      context: .
      dockerfile: docker/php.dockerfile
    image: jez500/pricebuddy:latest
    container_name: price-buddy
    ports:
      - 8090:80
    volumes:
      - ${ROOT}/config/pricebuddy:/app/storage
      - ./.env:/app/.env
    environment:
      DB_HOST: database                       # Name of the database service
      DB_USERNAME: pricebuddy                 # Should match the MYSQL_USER in the database service
      DB_PASSWORD: ${DB_PASSWORD}                 # Should match the MYSQL_PASSWORD in the database service
      DB_DATABASE: pricebuddy                 # Should match the MYSQL_DATABASE in the database service
      APP_USER_EMAIL: email@addresss.com       # Only used for seeding the database
      APP_USER_PASSWORD: ${USER_PASSWORD}                # Only used for seeding the database
      SCRAPER_BASE_URL: http://scraper:3030   # Url to Name of the scrapper service
    depends_on:
      - database
      # networks:
      #     - default

  database:
    image: mysql:8.2
    container_name: price-buddy-db
    environment:
      MYSQL_DATABASE: pricebuddy
      MYSQL_USER: pricebuddy
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ${ROOT}/config/pricebuddy/database:/var/lib/mysql
    # networks:
    #     - default

  scraper:
    container_name: price-buddy-scraper
    image: amerkurev/scrapper:latest
    # networks:
    #     - default
    ports:
      - 3030:3030 # Optional, if you want to access the scrapper api from the host machine
```

**Comment by janstadt** [comment]
I also tried mapping the volumes in the docker-compose files to a specific path locally but im getting the same error.

```
volumes:
  storage:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${ROOT}/config/pricebuddy
  database:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${ROOT}/config/pricebuddy/database
```

**Comment by janstadt** [comment]
Ok got it working:

```
services:

  app:
    build:
      context: .
      dockerfile: docker/php.dockerfile
    image: jez500/pricebuddy:latest
    container_name: pricebuddy
    ports:
      - 8880:80
    volumes:
      - storage:/app/storage
      - ./.env:/app/.env
    environment:
      PUID: 99
      PGID: 100
      DB_HOST: database                       # Name of the database service
      DB_USERNAME: pricebuddy                 # Should match the MYSQL_USER in the database service
      DB_PASSWORD: ${DB_PASSWORD}                 # Should match the MYSQL_PASSWORD in the database service
      DB_DATABASE: pricebuddy                 # Should match the MYSQL_DATABASE in the database service
      APP_USER_EMAIL: email@address.com       # Only used for seeding the database
      APP_USER_PASSWORD: ${USER_PASSWORD}                # Only used for seeding the database
      SCRAPER_BASE_URL: http://scraper:3000   # Url to Name of the scrapper service
    depends_on:
      - database
    networks:
      - password-buddy-default
    # user: 99:100

  database:
    # user: 99:100  
    image: mysql:8.2
    container_name: pricebuddy-db    
    environment:
      PUID: 99
      PGID: 100    
      MYSQL_DATABASE: pricebuddy
      MYSQL_USER: pricebuddy
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - database:/var/lib/mysql
    networks:
      - password-buddy-default

  scraper:
    # user: 99:100  
    container_name: pricebuddy-scraper  
    image: amerkurev/scrapper:latest
    networks:
      - password-buddy-default
    ports:
      - 3030:3000 # Optional, if you want to access the scrapper api from the host machine

volumes:
  storage:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${ROOT}/config/pricebuddy
  database:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${ROOT}/config/pricebuddy/database
networks:
    password-buddy-default:

```
