### ISSUE TITLE
Bug: Incorrect Currency Formatting with international Locales

### ISSUE THREAD

**Issue by mariosemes** [jez500/pricebuddy#29]
**Description:**  
As previously discussed on Reddit, I would like to report an issue with international currency formatting when using the `fr_FR` locale.  

In the current setup, prices such as `12,12€` are incorrectly displayed as `$1,212.00`.  

**Steps Taken:**  
I attempted to set `APP_CURRENCY_LOCALE=fr_FR` in both the `docker-compose` configuration and the `.env` file, but this did not resolve the issue.  

**Example for Testing:**  
You can see this behavior on the following page:  
[https://mandispharmljekarne.hr/boston-simplus-kombi-otopina-120ml-proizvod-403/](https://mandispharmljekarne.hr/boston-simplus-kombi-otopina-120ml-proizvod-403/)  

**Expected Behavior:**  
Prices should be displayed using the correct locale format (e.g., `12,12€` for `fr_FR`).  

Thank you for your attention to this issue.  

p.s. `fr_FR` was taken only for example as an international formating. Should be the same for any other European country locale.

**Comment by JarbasAl** [comment]
related https://github.com/jez500/pricebuddy/issues/20 and https://github.com/jez500/pricebuddy/issues/15

**Comment by ABCAV** [comment]
Same for me from the UK; I've tried `APP_CURRENCY_LOCALE: en_GB` and `en-GB` and it still gets formatted as `$` instead of `£ (GBP)`.

Here's a link to try:
https://www.amazon.co.uk/dp/B07LH55GC2?tag=synack-21

**Comment by jez500** [comment]
I'm working on this atm, stay tuned!

**Comment by ABCAV** [comment]
Happy to help test, just holler. Also, are you accepting feature requests..? Thinking alternative notification intgegrations, specifically Gotify ;)

**Comment by jez500** [comment]
re-opening for testing feedback

**Comment by janaxhell** [comment]
Coming from https://github.com/jez500/pricebuddy/issues/18 

Just deployed latest build and in Locale I cannot scroll beyond Bahamian Dollar, so I cannot set EUR.

![Image](https://github.com/user-attachments/assets/16a3fd24-3493-45db-a52a-f4147462b87f)

Also tried to change to it_IT (Italian), but this has no effect on currency choice.

**Comment by jez500** [comment]
@janaxhell You should be able to search in that dropdown, its a pretty long list so it limits the number if items to display without searching

**Comment by janaxhell** [comment]
Ahh, ok, got it, it works, I've entered EUR with keyboard and it appeared. Thanks

**Comment by ABCAV** [comment]
OK so I've pulled the latest image and added en as locale and GBP £ as currency in both settings and in the Amazon UK entry under Stores and it's using the correct symbol but the price is still 0.01 and there's no image loaded. For AliExpress the price is also £0.01 but the image does load.

Is there a process for tweaking what is being scraped, or maybe I've misconfigured the scraper entirely (that is a possibility; I'm have Traefik reverse proxy enabled for both Pricebuddy and the scraper, with both on a proxy docker network as well as default).

Test URLs are:

https://www.amazon.co.uk/dp/B07LH55GC2
https://www.aliexpress.com/item/1005005762250227.html

**Comment by maksm** [comment]
Pulled the latest image, set the locale to my preferences and everything works ok 👍 

My test case was https://www.zoohit.si/shop/macke/suha_macja_hrana/royal_canin/care_nutriation/503017?activeVariant=503017.3

![Image](https://github.com/user-attachments/assets/48519332-a18d-4240-929c-ca995369c1d4)

Thanks for the effort, love the project, might contribute with some ideas and PRs for my use cases if that is ok.

**Comment by janaxhell** [comment]
Added the same exact product using the above link and in my case it shows like this:

![Image](https://github.com/user-attachments/assets/255dea51-364d-4cd4-92b1-93004c594eb6)

**Comment by ABCAV** [comment]
OK, so some sites seem to work great, some not - is there a guide to tweaking the scraper parameters, looks like it's just parsing some incorrect fields:

![Image](https://github.com/user-attachments/assets/2a89974c-680c-4765-b177-093a3cb20475)

**Comment by maksm** [comment]
> Added the same exact product using the above link and in my case it shows like this:
> 
> ![Image](https://github.com/user-attachments/assets/255dea51-364d-4cd4-92b1-93004c594eb6)

Hey in my case I modified the price selector to select the price for 4kg offering, so that is why we are getting different results. But the formatting is correct in your case.

**Comment by janaxhell** [comment]
> Hey in my case I modified the price selector to select the price for 4kg offering, so that is why we are getting different results. But the formatting is correct in your case.

If I click on the link you posted, I'm led to a page showing the 4Kg pack for 62.49€, same if I click on the added product on Pricebuddy. I've added the link as is, so something is wrong anyway.

**Comment by maksm** [comment]
> > Hey in my case I modified the price selector to select the price for 4kg offering, so that is why we are getting different results. But the formatting is correct in your case.
> 
> If I click on the link you posted, I'm led to a page showing the 4Kg pack for 62.49€, same if I click on the added product on Pricebuddy. I've added the link as is, so something is wrong anyway.

You need to change the css selector in the Stores part of pricebuddy and use this css selector in the Price strategy part: 

`.SelectedArticleBox_selectedArticle__TYxbk .z-product-price__amount[data-zta="reducedPriceAmount"]`

![Image](https://github.com/user-attachments/assets/3c8891a8-270a-4950-8ba9-f413a494e224)

**Comment by janaxhell** [comment]
Ok, yes, in this case it matches. So I confirm as well that some sites are fine and others aren't.

**Comment by CodeBradley** [comment]
> OK so I've pulled the latest image and added en as locale and GBP £ as currency in both settings and in the Amazon UK entry under Stores and it's using the correct symbol but the price is still 0.01 and there's no image loaded. For AliExpress the price is also £0.01 but the image does load.
> 
> Is there a process for tweaking what is being scraped, or maybe I've misconfigured the scraper entirely (that is a possibility; I'm have Traefik reverse proxy enabled for both Pricebuddy and the scraper, with both on a proxy docker network as well as default).
> 
> Test URLs are:
> 
> https://www.amazon.co.uk/dp/B07LH55GC2 https://www.aliexpress.com/item/1005005762250227.html

Can you share your config file? I'm getting mixed content warnings when I'm using traefik, even with APP_URL set to https://${DOMAIN}. Wondering what you might've done different?

**Comment by ABCAV** [comment]
Sure: I put all three containers on my proxy network to work with traefik and added labels to the main and scraper ones (in case I wanted to test the scraper separately)...


```
services:
  app:
    build:
      context: .
      dockerfile: docker/php.dockerfile
    image: jez500/pricebuddy:latest
#        ports:
#            - 8080:80
    volumes:
      - /home/docker/pricebuddy/storage:/app/storage
      - /home/docker/pricebuddy/.env:/app/.env
    environment:
      DB_HOST: database                       # Name of the database service
      DB_USERNAME: pricebuddy                 # Should match the MYSQL_USER in the database service
      DB_PASSWORD: pric3buddy                 # Should match the MYSQL_PASSWORD in the database service
      DB_DATABASE: pricebuddy                 # Should match the MYSQL_DATABASE in the database service
      APP_USER_EMAIL: youremail@domain.com       # Only used for seeding the database
      APP_USER_PASSWORD: admin                # Only used for seeding the database
      APP_CURRENCY_LOCALE: en_GB
      SCRAPER_BASE_URL: http://pricebuddy-scraper.local.yourdomain.com   # Url to Name of the scrapper service
#      SCRAPER_BASE_URL: http://pricebuddy-scraper:3000   # Url to Name of the scrapper service
      AFFILIATE_ENABLED: false                 # See https://pricebuddy.jez.me/support-project.html
    depends_on:
      - database
    networks:
      - default
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pricebuddy.entrypoints=http"
      - "traefik.http.routers.pricebuddy.rule=Host(`pricebuddy.local.yourdomain.com`)"
      - "traefik.http.middlewares.pricebuddy-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.pricebuddy.middlewares=pricebuddy-https-redirect"
      - "traefik.http.routers.pricebuddy-secure.entrypoints=https"
      - "traefik.http.routers.pricebuddy-secure.rule=Host(`pricebuddy.local.yourdomain.com`)"
      - "traefik.http.routers.pricebuddy-secure.tls=true"
      - "traefik.http.routers.pricebuddy-secure.service=pricebuddy"
      - "traefik.http.services.pricebuddy.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

  database:
    image: mysql:8.2
    environment:
      MYSQL_DATABASE: pricebuddy
      MYSQL_USER: pricebuddy
      MYSQL_PASSWORD: pric3buddy
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/docker/pricebuddy/database:/var/lib/mysql
    networks:
      - default
      - proxy

  scraper:
    image: amerkurev/scrapper:latest
    networks:
      - default
      - proxy
#    ports:
#      - 3030:3000 # Optional, if you want to access the scrapper api from the host machine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pricebuddy-scraper.entrypoints=http"
      - "traefik.http.routers.pricebuddy-scraper.rule=Host(`pricebuddy-scraper.local.yourdomain.com`)"
      - "traefik.http.middlewares.pricebuddy-scraper-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.pricebuddy-scraper.middlewares=pricebuddy-scraper-https-redirect"
      - "traefik.http.routers.pricebuddy-scraper-secure.entrypoints=https"
      - "traefik.http.routers.pricebuddy-scraper-secure.rule=Host(`pricebuddy-scraper.local.yourdomain.com`)"
      - "traefik.http.routers.pricebuddy-scraper-secure.tls=true"
      - "traefik.http.routers.pricebuddy-scraper-secure.service=pricebuddy-scraper"
      - "traefik.http.services.pricebuddy-scraper.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"

volumes:
  storage:
  database:

networks:
  proxy:
    external: true
  default:
```
