### ISSUE TITLE
CSS Styles not loading

### ISSUE THREAD

**Issue by cblinq** [jez500/pricebuddy#73]
This is the issue:

<img width="1079" alt="Image" src="https://github.com/user-attachments/assets/7f1fe6d6-443f-4b51-849f-8f774e918b0e" />

This is my docker compose:

```
services:

    tsdproxy:
      image: almeidapaulopt/tsdproxy:latest
      container_name: tsdproxy
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - tsdproxydata:/data
      environment:
        - TSDPROXY_AUTHKEY=
        - TSDPROXY_HOSTNAME=
        - DOCKER_HOST=unix:///var/run/docker.sock
      restart: unless-stopped


    app:
        labels:
          tsdproxy.enable: "true"
          tsdproxy.name: "pricebuddy"
        build:
            context: .
            dockerfile: docker/php.dockerfile
        image: jez500/pricebuddy:latest
        volumes:
            - storage:/app/storage
            - ./.env:/app/.env
        environment:
            DB_HOST: database                       # Name of the database service
            DB_USERNAME: pricebuddy                 # Should match the MYSQL_USER in the database service
            DB_PASSWORD: pric3buddy                 # Should match the MYSQL_PASSWORD in the database service
            DB_DATABASE: pricebuddy                 # Should match the MYSQL_DATABASE in the database service
            APP_USER_EMAIL: admin@example.com       # Only used for seeding the database
            APP_USER_PASSWORD: admin                # Only used for seeding the database
            SCRAPER_BASE_URL: http://scraper:3000   # Url to Name of the scrapper service
            AFFILIATE_ENABLED: 'true'               # See https://pricebuddy.jez.me/support-project.html
        depends_on:
            database:
                condition: service_healthy

  database:
        image: mysql:8.2
        environment:
            MYSQL_DATABASE: pricebuddy
            MYSQL_USER: pricebuddy
            MYSQL_PASSWORD: pric3buddy
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - database:/var/lib/mysql
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 1m

    scraper:
        image: amerkurev/scrapper:latest


volumes:
  tsdproxydata:
  storage:
  database:

```

I added tsdproxy which proxies the container to my tailscale network, should not affect this at all and only removed the ports because I will not use this outside the tailnet and also removed the default network.
