### ISSUE TITLE
Aliexpress price scrapping

### ISSUE THREAD

**Issue by Dinth** [jez500/pricebuddy#77]
Hi. Im trying to do price scrapping from aliexpress. While the title and image get pulled correctly out of the box (they are in page metadata), the price was not - in fact the document returned by curl doesnt seem to contain the price at all.

What i have do is enabled scrapper scrapping, with device=Desktop Firefox and the following regexp for the price:
`~\"priceCurrency\":\"[A-Z]+?\",\"price\":\"(\d.+?)\"~`
That seems to work for me, at least at this moment in time. 
The problem im expecting to see here is with the currency. From my experience, when i open aliexpress link in my normal desktop browser, it serves a page with the correct locale set... until it doesnt, and out of the blue starts serving me pages in italian with euro currency or polish with PLN currency. Obviously this is something i would like to avoid when monitoring prices automatically, so im wondering - does anyone know how to force Aliexpress to **always** open a link with the chosen locale/currency?

**Comment by matbgn** [comment]
Hi @Dinth, What was your method/config (I guess you use Docker right?) for successfully rendering the JavaScript to extract these values? No matter what I do, I'm consistently running into an issue where the JavaScript is not being fully resolved. Consequently, the price field and other values are not available to my scraper. 

![Image](https://github.com/user-attachments/assets/07323545-f01c-4c07-acf8-5aa9eda9c3a1)

**Comment by Dinth** [comment]
Do you have scrapper installed?
Here's my docker-compose, i had same problem as you, until i selected "Browser based request", now its working fine.
```
services:
  pricebuddy:
    build:
      context: .
      dockerfile: docker/php.dockerfile
    image: jez500/pricebuddy:latest
    ports:
      - 5757:80
    volumes:
      - /opt/docker/pricebuddy/pricebuddy_data:/app/storage
    environment:
      DB_HOST: "pricebuddy-mysql"
      DB_USERNAME: "pricebuddy"
      DB_PASSWORD: "${PRICEBUDDY_DB_PASS}"
      DB_DATABASE: "pricebuddy"
      APP_USER_EMAIL: "${ADMIN_EMAIL}"
      APP_USER_PASSWORD: "${PRICEBUDDY_ADMIN_PASS}"
      SCRAPER_BASE_URL: "http://pricebuddy-scraper:3000"
      AFFILIATE_ENABLED: "false"
    depends_on:
      - pricebuddy-mysql
    labels:  
      traefik.enable: "true"
      traefik.http.routers.pricebuddy.rule: "Host(`prices.${DOMAIN_NAME}`)"
      traefik.http.routers.pricebuddy.entrypoints: "websecure"
      traefik.http.routers.pricebuddy.tls: "true"
      traefik.http.routers.pricebuddy.tls.certresolver: "letsencrypt"
      traefik.http.routers.pricebuddy.tls.domains[0].main: "${DOMAIN_NAME}"
      traefik.http.routers.pricebuddy.tls.domains[0].sans: "*.${DOMAIN_NAME}"
      traefik.http.services.pricebuddy.loadbalancer.server.port: "80"
      homepage.group: "Home"
      homepage.name: "Pricebuddy"
      homepage.icon: "sh-pricebuddy.png"
      homepage.href: "https://prices.${DOMAIN_NAME}"
      homepage.description: "Price tracker"
    networks:
      - pricebuddy
      - traefik

  pricebuddy-mysql:
    image: mysql:8.2
    environment:
      MYSQL_DATABASE: "pricebuddy"
      MYSQL_USER: "pricebuddy"
      MYSQL_PASSWORD: "${PRICEBUDDY_DB_PASS}"
      MYSQL_ROOT_PASSWORD: "${PRICEBUDDY_DB_ADMIN_PASS}"
    volumes:
      - /opt/docker/pricebuddy/pricebuddy_mysql:/var/lib/mysql
    networks:
      - pricebuddy

  pricebuddy-scraper:
    image: amerkurev/scrapper:latest
    networks:
      - pricebuddy
#    ports:
#      - 3030:3000
networks:
  pricebuddy:
    name: pricebuddy
    driver: bridge
    external: false
  traefik:
    external: true
```
